### ISSUE TITLE
Using forumEmbedTopic, getting wrong counts for replies

### ISSUE THREAD

**Issue by flips** [rainlab/forum-plugin#72]
When I create a new post, it starts out as having '-1' replies in the forum I created for forum posts.
I was following the tutorial here: https://vimeo.com/97088926

I guess something's changed for counting from 0 or from 1 or something ...
(I have three posts, listed as three forum topics, one with -1 comments, two with 0 -- while in reality they have 0 and 1 comments ...)

_(PHP 5.6.9-0+deb8u1, Debian 8, October CMS Built 271, Forum plugin v1.0.14)_

**Comment by billyzduke** [comment]
I am seeing this as well, still, a year after original post. I suppose counting "replies" rather than posts means that the first post in a topic should show a replies value of zero, which it does. Just need to add a simple if statement to Twig template /components/channel/topics.htm to make sure values less than zero get reset to zero. In my personal version, I've changed "replies" to "posts" and removed the -1 from topic.count_posts (in custom partial copied over to active theme).

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
