### ISSUE TITLE
Add support for Tags

### ISSUE THREAD

**Issue by LaravelNick** [rainlab/forum-plugin#93]
Surprised that this plugin doesn't seem to support Tags, unless I've missed something.

This would be a very useful feature to group topics together and help users find questions that have already been asked.

**Comment by daftspunk** [comment]
Can you provide a detailed description on how this feature would work?

**Comment by Teranode** [comment]
@daftspunk basically when you are creating a topic, below the subject field there would be a way to enter tags (keywords) and separate them by comma or pipes (or whatever preset separator you can define) in the tag field. 

One topics are created you can display the tags, and you are able to find topics based on the title or tags a user has posted.

in short it's basically the backend version of taglist, except without relations and just custom words being inputted by a user.

With that being said, a good start to this would be to limit how many tags a user could make per forum (or globally if you have global settings for things). You shouldn't focus on it now, but rather make backend settings for global things when you have the time, as it could benefit user restrictions in the long run.

**Comment by daftspunk** [comment]
Is this really a common feature? I can't remember the last time I was asked to enter tags when submitting content to a website. Pretty sure the tag concept has gone the way of the dinosaur.

**Comment by Teranode** [comment]
Its more of something users wanted because they wanted an easier way to organize their threads by tags and such, some forum software have plugins and others have it integrated because users wanted it.

When i think of tags i kinda think of when users or administrators direct users to put like:
```
[Topic Tag] Topic Title
```
You know, those kinds of tags, which are still being used, then there are the tags that have multiple keywords in the previous post I mentioned. Other times they're both there (IDK why one is good enough, but i get the other ne is pretty specific for categorizing), anyway it's up to you if you want to add it or not.

**Comment by daftspunk** [comment]
Thanks! We should pass on this because it competes too much with categories. Most other forums do use tags in this way, feel free to fork this one, remove categories and replace with tags.
